### ISSUE TITLE
Compile Yolo with Ariadne

### ISSUE THREAD

**Issue by ghost** [m4nh/cables_dataset#1]
Hi,
great work with Ariadne. I found your paper by chance. I have studied it and want to ask how did you compile yolo with Ariadne which you mentioned in your paper?

Thank you in advance!

**Comment by m4nh** [comment]
Hi @WellML , what do u mean with "compile"?

**Comment by ghost** [comment]
Hi @m4nh, I mean after training and detecting the endpoints of the cable with yolo, how can I tell Ariadne to automatically use these endpoints as starting points for the iterative process?

Best regards

**Comment by ghost** [comment]
To be more specific, I refer to your paper on page 10, 3.3. How has been this achieved in detail in the python code?

"the endpoint detection step predicts a set of bounding boxes ˆyi around the actual endpoints. For each such prediction we find the
superpixel containing the central point of the box. The graph vertex vi corresponding to this superpixel is marked as a seed to start a new walk."

**Comment by m4nh** [comment]
ok.. if you launch the demo script (`manual_path_finder.py`), now, you have to click with mouse to the `start` and `end` points. Both are a `(x,y)` pair. With YOLO you have a set of box predictions like `(x,y,w,h)` , you can use a pair of YOLO prediction, only the x,y coordinates, to define a `start` and an `end` point replacing the mouse callback in abovementioned script

**Comment by ghost** [comment]
Thank you for your answer. Since I am interested in developing your code and have further questions, is it possible to stay in contact via email or phone/skype?

**Comment by m4nh** [comment]
sure, my email is in the referenced paper
